// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhwawxqjfdvkcryeeefz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJod2F3eHFqZmR2a2NyeWVlZWZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNTk3MTIsImV4cCI6MjA1OTkzNTcxMn0.am1JJjOilGaRKkYvE2RL37GAF_1l5nM7t-dwIBBpj0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);